name: RoyalShops
main: io.mooshe.shops.MainPlugin
version: 0.5
depend: [Vault, Citizens]
commands:
  trader:
    description: All commands related to the Trader trait for Citizens
    usage: /trader help
    permission: citizens.shop.admin
    permission-message: You do not have sufficient permission to use this command.
